Exception in thread "main" java.lang.NullPointerException
	at Main.testBug2849731_2(Main.java:22)
	at Main.main(Main.java:12)
